fmt

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -13,14 +13,13 @@ mkdir -p "$ASDF_DOWNLOAD_PATH"
 # TODO: Adapt this to proper extension and adapt extracting strategy.
 release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
 
-
 # Download tar.gz file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 echo "This is the download path contents in $ASDF_DOWNLOAD_PATH before extraction"
 ls "${ASDF_DOWNLOAD_PATH}"
 
 #  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH"  || fail "Could not extract $release_file"
+tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
 # Remove the tar.gz file since we don't need to keep it
 
 echo "This is the download path contents in $ASDF_DOWNLOAD_PATH AFTER extraction"
